### ISSUE TITLE
eBook format

### ISSUE THREAD

**Issue by MikeTaylor** [vufind-org/learning-vufind-book#4]
It would be great if this could be compiled into an `.epub` or `.mobi`.

**Comment by demiankatz** [comment]
Thanks for the suggestion, @MikeTaylor. Fortunately, Sphinx supports epub output, so I have just made a new release that includes both ePub and PDF versions of the document.

**Comment by MikeTaylor** [comment]
Well, that is amazing! Thank you so much!

**Comment by MikeTaylor** [comment]
![PXL_20221024_133429872](https://user-images.githubusercontent.com/212761/197540112-1156e39a-1897-4f57-90b1-a10d329b3728.jpg)

**Comment by demiankatz** [comment]
Very nice! Glad I could help. :-)
